plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'com.vanniktech.maven.publish' version '0.34.0'
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
}

group = 'io.github.tcq1007'
version = '0.0.1'
description = 'Spring Boot utils'

repositories {
    maven { url 'https://maven.aliyun.com/repository/public' }
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        mavenBom "com.querydsl:querydsl-bom:${querydslVersion}"
    }
    dependencies {
        dependency "org.apache.commons:commons-lang3:${commonsLang3Version}"
        dependency "commons-io:commons-io:${commonsIoVersion}"
    }
}

dependencies {
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-core'
    implementation 'org.springframework.boot:spring-boot'
    compileOnly 'org.springframework.data:spring-data-commons'
    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
    compileOnly 'org.springframework.boot:spring-boot-starter-data-jpa'
    compileOnly 'org.springframework.boot:spring-boot-persistence'
    compileOnly 'org.apache.commons:commons-lang3'
    compileOnly 'org.slf4j:slf4j-api'
    compileOnly 'com.querydsl:querydsl-jpa::jakarta'
    compileOnly 'tools.jackson.core:jackson-databind'
    compileOnly 'commons-io:commons-io'
    compileOnly 'org.springframework.cloud:spring-cloud-context'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    api 'nl.talsmasoftware:lazy4j:2.0.5'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
    failOnError = false
}

tasks.named('test') {
    useJUnitPlatform()
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    pom {
        name = 'springboot-utils'
        description = project.description
        inceptionYear = '2026'
        url = 'https://github.com/TCQ1007/springboot-utils'
        licenses {
            license {
                name = 'The Apache License, Version 2.0'
                url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                distribution = 'repo'
            }
        }
        developers {
            developer {
                id = 'TCQ1007'
                name = 'tcq1007'
                email = '1007281088@qq.com'
                url = 'https://github.com/TCQ1007'
            }
        }
        scm {
            connection = 'scm:git:git://github.com/TCQ1007/springboot-utils.git'
            developerConnection = 'scm:git:ssh://git@github.com/TCQ1007/springboot-utils.git'
            url = 'https://github.com/TCQ1007/springboot-utils'
        }
    }
}

signing {
    required = {
        gradle.taskGraph.allTasks.any { task ->
            task.name.toLowerCase().contains('mavencentral')
        }
    }
    useGpgCmd()
}

publishing {
    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/TCQ1007/springboot-utils')
            credentials {
                username = findProperty('gpr.user') ?: System.getenv('GITHUB_ACTOR') ?: 'TCQ1007'
                password = findProperty('gpr.token') ?: System.getenv('GITHUB_TOKEN') ?: System.getenv('GH_TOKEN')
            }
        }
    }
}
